# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Posts
    url: '#posts'
    weight: 20
  - name: Projects
    url: '#projects'
    identifier: projects
    weight: 30
  - name: Overview
    parent: projects
    url: '#projects'
    weight: 31
  - name: Group Face-to-face interactions
    parent: projects
    url: project/face-to-face/
    weight: 31
  - name: Dynamics on higher-order networks
    parent: projects
    url: project/dynamics-on-hon
    weight: 32
  - name: Epidemic modeling
    parent: projects
    url: project/epidemics
    weight: 33
  - name: Tools and algorithms
    parent: projects
    url: project/tools
    weight: 34
  - name: Publications
    url: '#featured'
    weight: 50
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
